config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :attendances, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'

  get 'sign_up',  to:  'users#new'
  get 'login',  to:  'sessions#new'
  post 'login' ,  to: 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'

  get 'invite' ,  to: 'attendances#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'attendee_id'
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'attended_event_id'

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "user_id"
    has_many :attendances, foreign_key: "attended_event_id"
    has_many :attendees, class_name: "User", through: :attendances 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, foreign_key:"user_id"
    has_many :attendances, foreign_key: ":attendee_id"
    has_many :attended_events, class_name: "Event", through: :attendances 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :display_button_new
    helper_method :display_button_log
    helper_method :display_username
    helper_method :user_validation


    def current_user
      User.find_by(id: session[:user_id])
    end

    def display_username
      return current_user.username if current_user
    end
  
    def display_button_log
      if current_user.present?
        return display_username
      else
        "<a class='button is-success' href='/login'>Sign in</a>".html_safe
      end
    end

    def user_validation
      if current_user.present?
        return "<a class='button is-danger' href='/logout'>Log out</a>".html_safe
      else
        "<a class='button is-success' href='/sign_up'>Sign up</a>".html_safe
      end
    end
  
    def display_button_new
      return "<a class='button is-success' href='/events/new'>NEW EVENT</a>".html_safe if current_user.present?
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    include EventsHelper

    def new
        @attendance = Attendance.new()
    end

    def create
        @event = Event.find(event_params)
        @attendance = Attendance.new(event_id: @event.id, user_id: params[:user_id])

        if @attendance.save
          flash[:success] = "Invite successfully created"
          redirect_to event_path
        else
          flash[:error] = "Something went wrong"
        end
    end
    
    
    def update
        @attendance = Attendance.find(params[:id])
        if @attendance.update_attributes(params[:attendance])
          flash[:success] = "Object was successfully updated"
          redirect_to event_path
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @creator = User.find(@event.user_id).username
    @user = User.all
    @attendance = Attendance.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :description, :location, :user_id)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new; end
    
    def create
        user = User
                .find_by(email: params["email"])
        if user
            session[:user_id] = user.id
            redirect_to root_path
        else
            render json: { status: 401 }
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: 'Logged out!'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Object successfully created"
            session[:user_id] = @user.id
            redirect_to root_path
        else
            flash[:error] = "Something went wrong"
            render 'new'
        end
    end

    def show
        @user = User.find(session[:user_id])
        @events = Event.all
    end
    
    private 

    def user_params
        params.require(:user).permit(:username, :email)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :description, :location, :user_id)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/new.html.erb
<p>Jajaja</p>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		<div class="column is-4">
            <h1>Editing Event</h1>

            <%= render 'form', event: @event %>

            <%= link_to 'Show', @event %> |
            <%= link_to 'Back', events_path %>
			
		</div>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		<div class="column is-6">
			
		<p id="notice"><%= notice %></p>

      <h1 class='title is-4'>Events</h1>
      
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td><%= event.description %></td>
              <td><%= link_to 'Show', event %></td>
              <td><%= link_to 'Edit', edit_event_path(event) %></td>
              <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      <%= display_button_new %>
		</div>
		</div>
	</div>
</div>

app/views/events/new.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		<div class="column is-4">
			
            <h1>New Event</h1>

            <%= render 'form', event: @event %>

            <%= link_to 'Back', events_path %>
		</div>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<div class="section">
	<div class="container">
    <div class="columns is-centered">

      <div class="column is-4">
        
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @event.name %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @event.date %>
        </p>

        <p>
          <strong>Location:</strong>
          <%= @event.location %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @event.description %>
        </p>

        <p>
          <strong>Creator:</strong>
          <%= @creator %>
        </p> 

        <%= link_to 'Edit', edit_event_path(@event) %> |
        <%= link_to 'Back', events_path %>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @user.each do |user| %>
              <tr>
                <td><%= user.username %></td>
                <td>
                  <% if @creator == current_user.username %>
                    <%= link_to 'Invite', invite_path %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
    <nav class="navbar is-dark">
        <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-4">Private Events</h1>
            <% end %>
            <div class="navbar-burger burger" data-target="navbarExample">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navbarExample" class="navbar-menu">
            <div class="navbar-end">
                <div class="field is-grouped mt-2 mr-2">
                    <div class='field is-grouped mt-2 mr-2'>
                    <p class='control'>
                        <%= display_button_log %>
                    </p>
                    <p class='control'>
                        <%= user_validation %>
                    </p>
                    </div>
                </div>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= render 'layouts/navbar'%>
    <div class="column">
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |form| %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		<div class="column is-4">
            <%= render 'form' %>
			
		</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		<div class="column is-4">
			
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Username:</strong>
        <%= @user.username %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @user.events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td><%= event.description %></td>
              <td><%= link_to 'Show', event %></td>
              <td><%= link_to 'Edit', edit_event_path(event) %></td>
              <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'Back', events_path %>
		</div>
		</div>
	</div>
</div>